### ISSUE TITLE
Unreadable rendering when using Dark theme

### ISSUE THREAD

**Issue by fperez** [executablebooks/jupyterlab-myst#84] opened 2023-02-15 02:01 UTC
### Describe the bug

This shows the problem - same notebook opened with MyST and "Classic" in dark mode:

![image](https://user-images.githubusercontent.com/57394/218908190-79dc254d-c52a-471a-b189-d78f9a1ad111.png)

### Reproduce the bug

Use dark theme.

**Comment by agoose77** [comment] 2023-02-15 08:18
Duplicate of #67

**Comment by agoose77** [comment] 2023-02-15 08:55
This was a super easy fix, which surprised me. Turns out that @rowanc1 et al. have already handled the hard part of implementing the dark theming!

**Comment by agoose77** [comment] 2023-02-15 10:33
@fperez can you try out https://mybinder.org/v2/gh/executablebooks/jupyterlab-myst/agoose77/fix-dark-mode?urlpath=lab and see if it works?

**Closed** 2023-02-15 15:15 UTC
Labels: bug

**Comment by rowanc1** [comment] 2023-02-15 15:20
Will get a styles-focused release out soon!! 🚀 Thanks for taking this on @agoose77.

**Comment by fperez** [comment] 2023-02-15 17:12
Hi @agoose77 - it seems you deleted your branch so the Binder doesn't resolve anymore:

```
Could not resolve ref for gh:executablebooks/jupyterlab-myst/agoose77/fix-dark-mode. Double check your URL. GitHub recently changed default branches from "master" to "main".
```

But I trust you :) Huge thanks for getting on this so quickly, and sorry I missed the fact it was a dupe!

Awesome work as always, much appreciated!

**Comment by agoose77** [comment] 2023-02-15 17:22
> Hi @agoose77 - it seems you deleted your branch so the Binder doesn't resolve anymore:
> 
> ```
> Could not resolve ref for gh:executablebooks/jupyterlab-myst/agoose77/fix-dark-mode. Double check your URL. GitHub recently changed default branches from "master" to "main".
> ```
> 
> But I trust you :) Huge thanks for getting on this so quickly, and sorry I missed the fact it was a dupe!
> 
> Awesome work as always, much appreciated!

Ah, we merged so it deleted the branch! Perhaps try main?
